spring:
  application:
    name: department-service  # Specifies the name of the Spring application (department-service)
  config:
    import: "optional:configserver:http://localhost:8088"  # Imports configuration from the external config server at the specified URL.
                                                           # The 'optional:' prefix indicates that the application will start even if the config server is unavailable.
