server:
  port: 8082  # Specifies the port on which the server will listen

# Configuration to register the service in the service registry (Eureka)
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/  # URL of the Eureka server where this service will register

# Log tracing configuration for Zipkin
management:
  tracing:
    sampling:
      probability: 1.0  # Sets the probability of tracing requests (1.0 means 100% of requests will be traced)
